export const babyproducts=[{
 
    id:1,
    productname:"Boys Maroon Graphic Print Shirt And Formal Set",
    image:
    'https://static.hopscotch.in/fstatic/product/202207/0ca90593-db57-45d2-a1d3-f6b7b79e816a_large.jpg?version=1657529790085&tr=w-480,c-at_max,n-normal',
    price:'₹1292',
    discription:'Material: 100% COTTON,The actual product may differ slightly in color from the one illustrated in the images',
    type:'dress',
    quantity:1,

},
{
    id:2,
    productname:"Girls Yellow Polka Dot Print T-shirt and Dungaree Set",
    image:
    'https://static.hopscotch.in/fstatic/product/202206/39503ebc-5ff9-4b09-ac5c-1aedab80d1bf_large.jpg?version=1654769812686&tr=w-480,c-at_max,n-normal',
    price:'₹2055',
    discription:'Material: 95% Cotton, 5% Spandex,The actual product may differ slightly in color from the one illustrated in the images.',
    type:'dress',
    quantity:1,
},{
    id:3,
    productname:"Girls Pink Sleeveless Floral print Slim Fit Party Dress",
    image:'https://static.hopscotch.in/fstatic/product/202009/255c917a-d2ab-405c-8d89-d970f4915aa0_large.jpg?version=1600440311996&tr=w-480,c-at_max,n-normal',
    price:'₹1567',
    discription:'Material: 65% Polyester, 35% Viscose,The actual product may differ slightly in color from the one illustrated in the images..',
    type:'dress',
    quantity:1,
},{
    id:4,
    productname:"Boys Gray Checkered Blazer and Pant Formal Set",
    image:'https://static.hopscotch.in/fstatic/product/202307/b77b0c90-c4f4-42c3-bab8-8a1fb8ad821d_large.jpg?version=1688527979745&tr=w-480,c-at_max,n-normal',
    price:'₹606',
    discription:'Top Material: 35% Cotton and 65% Polyester, Bottom Material: 35% Cotton and 65% Polyester,The actual product may differ slightly in color from the one illustrated in the images..',
    type:'dress',
    quantity:1,
},{
    id:5,
    productname:"Portable Baby Stroller(TRI-FOLDING TROLLEY)",
    image:'https://meemee.in/cdn/shop/products/Mee_Mee_Premium_Portable_Baby_Stroller_Pram_with_Compact_Tri-Folding_Trolley_-_Blue_320x.jpg?v=1650903010',
    price:'₹369',
    discription:'When your baby can discover the world safely, it adds hours of fun and engaging trips to both your days. Mee Mee Baby Pram Stroller with Compact Tri-folding lets your baby sit comfortably and feel safe to experience new sounds, movements, colors and shapes. Made to adhere to the highest safety standards, it keeps your baby comfortable and safe along normal, bumpy or unpaved paths while having a joyful ride. Ergonomically designed, keeping you in mind, so that you can open the stroller pram with one hand while holding on to your baby with the other hand. It has been equipped with a tri-folding trolley handle to allow you to pull along the stroller in the case your baby prefers to explore the world in your arms.',
    type:'baby stroller',
    quantity:1,
},{
    id:6,
    productname:"2 IN 1 Baby Stroller|BABY ROCKER STROLLER|",
    image:'https://meemee.in/cdn/shop/products/MeeMeePremium2in1BabyPramStrollerwithRockingFunctionBlue_550x.jpg?v=1665663584',
    price:'₹505',
    discription:'When your baby can discover the world safely, it adds hours of fun and engaging trips to both your days. Mee Mee Baby Rocker Pram lets your baby sit comfortably and feel safe to experience new sounds, movement, colors and shapes. Made to adhere to the highest safety standards, it keeps your baby comfortable and safe while having a joyful ride. It completes your life with many joys of parenthood.',
    type:'baby stroller',
    quantity:1,
},{
    id:7,
    productname:"Mini Baby toys with cute smile face Bob-omb [smile face]",
    image:'https://i.etsystatic.com/37391865/r/il/62652e/4926815783/il_794xN.4926815783_95aj.jpg',
    price:'₹916',
    discription:'Need a cute desk buddy or a new dashboard passenger? Standing an adorable 3 inches tall, this bob-omb will surely make any Mario collection stand out!',
    type:'toys',
    quantity:1,
},{
    id:8,
    productname:"Ratnas Happy Baby Cute Animal Rattle 5Pcs For Babies",
    image:'https://www.toysrus.in/media/catalog/product/cache/0a02c3039f9f94b26b587e518fdf737c/4/1/41_xem0ntys.jpg',
    price:'₹916',
    discription:'The figure I carefully made for Super Mario fans and animated character collectors is produced from resin and plastic material with a 3D printer.',
    type:'toys',
    quantity:1,
},{
    id:9,
    productname:"Baybee Natural Flow Baby Feeding Bottle 250Ml, Green",
    image:'https://www.toysrus.in/media/catalog/product/cache/0a02c3039f9f94b26b587e518fdf737c/b/0/b09rp7rxlz_1.jpg',
    price:'₹450',
    discription:'Need a cute desk buddy or a new dashboard passenger? Standing an adorable 3 inches tall, this bob-omb will surely make any Mario collection stand out!',
    type:'baby care',
    quantity:1,
},{
    id:10,
    productname:"Baybee Silicone Baby Spoon Set For Baby Feeding",
    image:'https://www.toysrus.in/media/catalog/product/cache/0a02c3039f9f94b26b587e518fdf737c/t/r/tru_2famazoncrawled_2fb0b65rhhcq_2fmonobrand_2fb0b65rhhcq_1.jpg',
    price:'₹650',
    discription:'Need a cute desk buddy or a new dashboard passenger? Standing an adorable 3 inches tall, this bob-omb will surely make any Mario collection stand out!',
    type:'baby care',
    quantity:1,
},{
    id:11,
    productname:"Sensorimotor Toys, Multicolour Toy With Colourful Rings",
    image:'https://clipart-library.com/images/BTgrnk5ac.jpg',
    price:'₹410',
    discription:'Need a cute desk buddy or a new dashboard passenger? Standing an adorable 3 inches tall, this bob-omb will surely make any Mario collection stand out!',
    type:'toys',
    quantity:1,
},{
    id:12,
    productname:"Baybee Silicone Baby Feeding Bowl With Lid, , Suction Cup",
    image:'https://www.toysrus.in/media/catalog/product/cache/0a02c3039f9f94b26b587e518fdf737c/b/0/b0b7nzbpvm_1.jpg',
    price:'₹399',
    discription:'Need a cute desk buddy or a new dashboard passenger? Standing an adorable 3 inches tall, this bob-omb will surely make any Mario collection stand out!',
    type:'baby care',
    quantity:1,
},{
    id:13,
    productname:"Babypie foldable remote control electric swing vibrating chair",
    image:'https://www.toysrus.in/media/catalog/product/cache/0a02c3039f9f94b26b587e518fdf737c/p/r/prod_2fproduct-image_2ftoys_2ftru_2fb0b3rw8jy9_2fb0b3rw8jy9_1.jpg',
    price:'₹7560',
    discription:'Need a cute desk buddy or a new dashboard passenger? Standing an adorable 3 inches tall, this bob-omb will surely make any Mario collection stand out!',
    type:'baby stroller',
    quantity:1,
},{
    id:14,
    productname:"Baybee Astro 2 In 1 Baby Walker | Round Kids Walker",
    image:'https://www.toysrus.in/media/catalog/product/cache/0a02c3039f9f94b26b587e518fdf737c/b/0/b09pr6mmpk_1.jpg',
    price:'₹6000',
    discription:'Need a cute desk buddy or a new dashboard passenger? Standing an adorable 3 inches tall, this bob-omb will surely make any Mario collection stand out!',
    type:'baby stroller',
    quantity:1,
},{
    id:15,
    productname:"Baybee Tableware Silicone Suction Plate For Kids",
    image:'https://www.toysrus.in/media/catalog/product/cache/0a02c3039f9f94b26b587e518fdf737c/p/r/prod_2fproduct-image_2ftoys_2ftru_2fimages_2fb0c33ddprs_2fb0c33ddprs_1.jpg',
    price:'₹916',
    discription:'Need a cute desk buddy or a new dashboard passenger? Standing an adorable 3 inches tall, this bob-omb will surely make any Mario collection stand out!',
    type:'baby care',
    quantity:1,
},{
    id:16,
    productname:"Talking Cactus Baby Storio Toys Dancing Cactus Talking Toy",
    image:'https://www.whatshop.in/cdn/shop/products/ToysTalkingCactusBaby4.jpg?v=1669697491',
    price:'₹916',
    discription:'Need a cute desk buddy or a new dashboard passenger? Standing an adorable 3 inches tall, this bob-omb will surely make any Mario collection stand out!',
    type:'toys',
    quantity:1,
},{
    id:17,
    productname:"Boys Yellow Text Print Full-Sleeve Bodysuit-1-30% Cotton",
    image:'https://static.hopscotch.in/fstatic/product/202203/1bfe047b-7f06-47b8-bd88-3743bcb4ba92_large.jpg?version=1646586090222&tr=w-480,c-at_max,n-normal',
    price:'₹700',
    discription:'Need a cute desk buddy or a new dashboard passenger? Standing an adorable 3 inches tall, this bob-omb will surely make any Mario collection stand out!',
    type:'dress',
    quantity:1,
},{
    id:18,
    productname:"Boys Blue Solid Full-Sleeve Romper-100% Cotton",
    image:'https://static.hopscotch.in/fstatic/product/201909/5ff11108-ca16-4e37-94ea-eb468b58c6d3_large.jpg?version=1567581309038&tr=w-480,c-at_max,n-normal',
    price:'₹600',
    discription:'Need a cute desk buddy or a new dashboard passenger? Standing an adorable 3 inches tall, this bob-omb will surely make any Mario collection stand out!',
    type:'dress',
    quantity:1,
},{
    id:19,
    productname:"Pampers All round Protection Pants Style Baby Diapers",
    image:'https://m.media-amazon.com/images/I/71i2N5NilxL._AC_UL480_QL65_.jpg',
    price:'₹699',
    discription:'Need a cute desk buddy or a new dashboard passenger? Standing an adorable 3 inches tall, this bob-omb will surely make any Mario collection stand out!',
    type:'baby care',
    quantity:1,
},{
    id:20,
    productname:"Pampers Active Baby Tape Style Baby Diapers, New Born",
    image:'https://m.media-amazon.com/images/I/61tdVb6CjGL._AC_UL480_QL65_.jpg',
    price:'₹916',
    discription:'Need a cute desk buddy or a new dashboard passenger? Standing an adorable 3 inches tall, this bob-omb will surely make any Mario collection stand out!',
    type:'baby care',
    quantity:1,
},{
    id:21,
    productname:"    Dash Discover Kids Tricycle with Music, Light, Storage",
    image:'https://m.media-amazon.com/images/I/61KxXWFYULL._AC_UL480_FMwebp_QL65_.jpg',
    price:'₹4599',
    discription:'Need a cute desk buddy or a new dashboard passenger? Standing an adorable 3 inches tall, this bob-omb will surely make any Mario collection stand out!',
    type:'baby cycle',
    quantity:1,
},{
    id:22,
    productname:"Dash Victor Tricycle for Kids, Baby Cycle, Kids Cycle",
    image:'https://m.media-amazon.com/images/I/71XyHnyIWXL._AC_UL480_FMwebp_QL65_.jpg',
    price:'₹1855',
    discription:'Need a cute desk buddy or a new dashboard passenger? Standing an adorable 3 inches tall, this bob-omb will surely make any Mario collection stand out!',
    type:'baby cycle',
    quantity:1,
},{
    id:23,
    productname:"Dash Teddy Foldable Tricycle/Cycle for Baby, Kids- 1",
    image:'https://m.media-amazon.com/images/I/61yP2nPB+KL._AC_UL480_QL65_.jpg',
    price:'₹2500',
    discription:'Need a cute desk buddy or a new dashboard passenger? Standing an adorable 3 inches tall, this bob-omb will surely make any Mario collection stand out!',
    type:'baby cycle',
    quantity:1,
},{
    id:24,
    productname:"Lifelong Trike Cycle for Kids Cycle 2 - 5 years - Tricycles",
    image:'https://m.media-amazon.com/images/I/61GaOdoS13L._AC_UL480_QL65_.jpg',
    price:'₹1050',
    discription:'Need a cute desk buddy or a new dashboard passenger? Standing an adorable 3 inches tall, this bob-omb will surely make any Mario collection stand out!',
    type:'baby cycle',
    quantity:1,
},{
    id:25,
    productname:"1House of Quirk Baby Bassinet Bedside Sleeper Cradle",
    image:'https://m.media-amazon.com/images/I/61fk7-lR6tL._AC_UL480_FMwebp_QL65_.jpg',
    price:'₹2916',
    discription:'Need a cute desk buddy or a new dashboard passenger? Standing an adorable 3 inches tall, this bob-omb will surely make any Mario collection stand out!',
    type:'baby stroller',
    quantity:1,
},{
    id:26,
    productname:"4-In-1 Stroller Pram Travel System with Car Seat",
    image:'https://hunyhuny.com/9766-large_default/Best-Strollers-Prams-Online.jpg',
    price:'₹12125',
    discription:'Need a cute desk buddy or a new dashboard passenger? Standing an adorable 3 inches tall, this bob-omb will surely make any Mario collection stand out!',
    type:'baby stroller',
    quantity:1,
},{
    id:27,
    productname:"House of Quirk Cradle Crib Baby Rack, Foldable",
    image:'https://m.media-amazon.com/images/I/61pGKm0ssRL._AC_UL480_FMwebp_QL65_.jpg',
    price:'₹3300',
    discription:'Need a cute desk buddy or a new dashboard passenger? Standing an adorable 3 inches tall, this bob-omb will surely make any Mario collection stand out!',
    type:'baby stroller',
    quantity:1,
},{
    id:28,
    productname:"12 In 1 Baby Cot Crib Oval |HunyHuny | Cot | Crib | Baby Cot ",
    image:'https://hunyhuny.com/5117-home_default/baby-crib-bed-oval-multifunction-milky-white.jpg',
    price:'₹916',
    discription:'Need a cute desk buddy or a new dashboard passenger? Standing an adorable 3 inches tall, this bob-omb will surely make any Mario collection stand out!',
    type:'baby stroller',
    quantity:1,
},{
    id:29,
    productname:"Pinewood Baby Bed 6-In-1 Multifunctional Rocking Cot",
    image:'https://hunyhuny.com/8864-home_default/Best-Baby-Cot-Bed-Online.jpg',
    price:'₹1200',
    discription:'Need a cute desk buddy or a new dashboard passenger? Standing an adorable 3 inches tall, this bob-omb will surely make any Mario collection stand out!',
    type:'baby stroller',
    quantity:1,
},{
    id:30,
    productname:"Maxi Cosi Iora Co-Sleeper | Beyond Graphite[BABY]",
    image:'https://cdn.shopify.com/s/files/1/0273/8778/9376/files/aasmdasdimf_360x.png?v=1703268237',
    price:'₹999',
    discription:'Need a cute desk buddy or a new dashboard passenger? Standing an adorable 3 inches tall, this bob-omb will surely make any Mario collection stand out!',
    type:'baby care',
    quantity:1,
},{
    id:31,
    productname:"Baby Moo's all-in-one Diaper Bag is the  all trades!",
    image:'https://babymoo.in/cdn/shop/products/603-PINKimg2.jpg?v=1623400792&width=300',
    price:'₹399',
    discription:'Need a cute desk buddy or a new dashboard passenger? Standing an adorable 3 inches tall, this bob-omb will surely make any Mario collection stand out!',
    type:'baby care',
    quantity:1,
},{
    id:32,
    productname:"Tropical Bliss Diaper Handbag-baby-travel bag",
    image:'https://motherlystore.com/cdn/shop/files/1_77d24538-ca00-424e-876e-dbbca439ec9f_400x400_crop_center.jpg?v=1691650403',
    price:'₹599',
    discription:'Need a cute desk buddy or a new dashboard passenger? Standing an adorable 3 inches tall, this bob-omb will surely make any Mario collection stand out!',
    type:'baby care',
    quantity:1,
},{
    id:33,
    productname:"Motherly Mini Magic Diaper Bag-Travel With Comfort",
    image:'https://motherlystore.com/cdn/shop/files/1_d9f0fade-b1c0-4f12-a71d-0db0a3c28372_400x400_crop_center.jpg?v=1697876411',
    price:'₹399',
    discription:'Need a cute desk buddy or a new dashboard passenger? Standing an adorable 3 inches tall, this bob-omb will surely make any Mario collection stand out!',
    type:'baby care',
    quantity:1,
},{
    id:34,
    productname:"Philips Avent Natural Bottle 125ml [feeding bottle]",
    image:'https://www.babyamore.in/wp-content/uploads/2022/03/Philips-Avent-NATURAL-2.0-BOTTLE-125ml-Single-INDIA-SCF03010..01-400x400.jpg',
    price:'₹499',
    discription:'Need a cute desk buddy or a new dashboard passenger? Standing an adorable 3 inches tall, this bob-omb will surely make any Mario collection stand out!',
    type:'baby care',
    quantity:1,
},{
    id:35,
    productname:"Avent Anti Colic Feeding Bottle- 260 ml, Twin Pack",
    image:'https://www.babyamore.in/wp-content/uploads/2022/03/Philips-Avent-Anti-Colic-Bottle-260ml-TwinPack-01-400x400.jpg',
    price:'₹499',
    discription:'Need a cute desk buddy or a new dashboard passenger? Standing an adorable 3 inches tall, this bob-omb will surely make any Mario collection stand out!',
    type:'baby care',
    quantity:1,
},{
    id:36,
    productname:"Girls Black Solid Top And Pant Set,50% Cotton, 50% Polyester",
    image:'https://static.hopscotch.in/fstatic/product/202207/ea9c74e6-710a-47ee-b95a-a1342dbf1bbf_large.jpg?version=1658383337158&tr=w-480,c-at_max,n-normal',
    price:'₹699',
    discription:'Need a cute desk buddy or a new dashboard passenger? Standing an adorable 3 inches tall, this bob-omb will surely make any Mario collection stand out!',
    type:'dress',
    quantity:1,
},{
    id:37,
    productname:"Girls Black Solid Blouse and Shorts Set, 95% Polyester",
    image:'https://static.hopscotch.in/fstatic/product/202401/7977ef5b-a8dc-4065-99e5-e1dab9854896_large.jpg?version=1704200644201&tr=w-480,c-at_max,n-normal',
    price:'₹899',
    discription:'Need a cute desk buddy or a new dashboard passenger? Standing an adorable 3 inches tall, this bob-omb will surely make any Mario collection stand out!',
    type:'dress',
    quantity:1,
},{
    id:38,
    productname:"Girls Beige Embroidered Blouse and Skirt Set",
    image:'https://static.hopscotch.in/fstatic/product/202311/b6dca486-b086-4b3c-9308-92f6e13a9415_large.jpg?version=1699362648506&tr=w-480,c-at_max,n-normal',
    price:'₹499',
    discription:'Need a cute desk buddy or a new dashboard passenger? Standing an adorable 3 inches tall, this bob-omb will surely make any Mario collection stand out!',
    type:'dress',
    quantity:1,
},{
    id:39,
    productname:"Unisex White Cut-Out Solid Sneaker, 100% Flyknit",
    image:'https://static.hopscotch.in/fstatic/product/202208/5a858c20-bbac-47d1-bfb0-30caaab16ee5_large.jpg?version=1660646123392&tr=w-480,c-at_max,n-normal',
    price:'₹799',
    discription:'Need a cute desk buddy or a new dashboard passenger? Standing an adorable 3 inches tall, this bob-omb will surely make any Mario collection stand out!',
    type:'shoes',
    quantity:1,
},{
    id:40,
    productname:"Girls Pink Bow Applique Led Boots,100% Synthetic",
    image:'https://static.hopscotch.in/fstatic/product/202301/4b417d5e-1319-4dd9-84a8-ba47dbafc5e3_large.gif?version=1672657808544&tr=w-480,c-at_max,n-normal',
    price:'₹799',
    discription:'Need a cute desk buddy or a new dashboard passenger? Standing an adorable 3 inches tall, this bob-omb will surely make any Mario collection stand out!',
    type:'shoes',
    quantity:1,
},{
    id:41,
    productname:"Girls White Text Print LED Slip Ons,LED lights are added",
    image:'https://static.hopscotch.in/fstatic/product/202307/630b4ee5-9a2f-4ef2-baa3-bb6562e875d3_large.gif?version=1688632275991&tr=w-480,c-at_max,n-normal',
    price:'₹1200',
    discription:'Need a cute desk buddy or a new dashboard passenger? Standing an adorable 3 inches tall, this bob-omb will surely make any Mario collection stand out!',
    type:'shoes',
    quantity:1,
},{
    id:42,
    productname:"Girls Pink Mesh Stripe Print LED Slip OnsLED lights are added",
    image:'https://static.hopscotch.in/fstatic/product/202301/bbc30c10-be1c-42b0-8fa6-4aa569fb2a24_large.gif?version=1672658411241&tr=w-480,c-at_max,n-normal',
    price:'₹888',
    discription:'Need a cute desk buddy or a new dashboard passenger? Standing an adorable 3 inches tall, this bob-omb will surely make any Mario collection stand out!',
    type:'shoes',
    quantity:1,
},{
    id:43,
    productname:"Infant Crochet Knitted Prewalker Booties - White",
    image:'https://static.hopscotch.in/fstatic/product/201808/5365d339-b3da-46fa-8929-b5e2a68f8d1f_large.jpg?version=1535104784824&tr=w-480,c-at_max,n-normal',
    price:'₹399',
    discription:'Need a cute desk buddy or a new dashboard passenger? Standing an adorable 3 inches tall, this bob-omb will surely make any Mario collection stand out!',
    type:'shoes',
    quantity:1,
},{
    id:44,
    productname:"Unisex Blue Stripes Print Led Slip-Ons,100% PVC",
    image:'https://static.hopscotch.in/fstatic/product/202304/ca184cbb-e9e0-4b5f-b1ab-14f627b5d103_large.gif?version=1681122866853&tr=w-480,c-at_max,n-normal',
    price:'₹899',
    discription:'Need a cute desk buddy or a new dashboard passenger? Standing an adorable 3 inches tall, this bob-omb will surely make any Mario collection stand out!',
    type:'shoes',
    quantity:1,
},{
    id:45,
    productname:"Girls Pink Applique Mary Jane,100% Fleece",
    image:'https://static.hopscotch.in/fstatic/product/202402/0726c980-0f40-4371-9ba2-fd4977f4cd20_large.jpg?version=1708343507612&tr=w-480,c-at_max,n-normal',
    price:'₹599',
    discription:'Need a cute desk buddy or a new dashboard passenger? Standing an adorable 3 inches tall, this bob-omb will surely make any Mario collection stand out!',
    type:'shoes',
    quantity:1,
}
 ];